// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofeejyihbnrawbrndctm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mZWVqeWloYm5yYXdicm5kY3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTU1MDEsImV4cCI6MjA2NDAzMTUwMX0.IsGzwl_b3ZGXBqT_ZahY_oaonU1R_8r9tErgW8oA9Tw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);